[package]
name = "learning-simd"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
panic = "abort"

[profile.test]
debug-assertions = true
debug = "full"
opt-level = 3

[dependencies]

[dev-dependencies]
criterion = { version = "0.8" }

[[bench]]
name = "count_spaces"
harness = false

[[bench]]
name = "base64"
harness = false
